# 应用名称
spring:
  application:
    name: Test
  mvc:
    static-path-pattern: /**
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

# 应用服务 WEB 访问端口
server:
  port: 10001
mail:
  #receivers: '于奎涛: 954513617@qq.com'
  receivers: '于奎涛: 1459047098@qq.com,
             李宁: ninglee5963@163.com,
             陈少华: 1573856670@qq.com,
             代北大: 714183040@qq.com,
             张全硕: zhangquanshuo1211@163.com,
             戴硕: 1605544014@qq.com,
             郭宁宁: 1970658387@qq.com'
  zipPath: /home/jkywhzh/work/
  type: jpg,jpeg,png,bmp,zip




